/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f6491758-fd26-4e6f-a251-71cd67d4aa7b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1KSMN1jHm",
    "aws_user_pools_web_client_id": "1licugfdkdcc15qcu4dcu4nji2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://npgplshvh5fflj2m6jpo7soxqu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gwz344gzuzhkha362cun3qi4di",
    "aws_user_files_s3_bucket": "amplify235842-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
