/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f6491758-fd26-4e6f-a251-71cd67d4aa7b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1KSMN1jHm",
    "aws_user_pools_web_client_id": "1licugfdkdcc15qcu4dcu4nji2",
    "oauth": {}
};


export default awsmobile;
